import {
  classifyCityProgrammaticRoute,
  type TopicPageRisk,
  type TopicRouteAuditItem,
  type TopicRouteConversionAction,
} from "@/lib/guide-engine-architecture";
import { cityProgrammaticPages, citySeoPath } from "@/lib/programmatic-seo";

const cityExampleSlug = "muscat";

export const entityRouteAuditInventory: TopicRouteAuditItem[] = [
  {
    routePattern: "/countries/[countrySlug]",
    examplePath: "/countries/oman",
    classification: "entity",
    conversionAction: "keep-as-entity",
    adminControlled: true,
    preserveIndexedUrl: true,
    risks: [],
    notes: "Country hub assembled from structured city, destination, guide, and attraction records.",
  },
  {
    routePattern: "/[citySlug]",
    examplePath: "/muscat",
    classification: "entity",
    conversionAction: "keep-as-entity",
    adminControlled: true,
    preserveIndexedUrl: true,
    risks: [],
    notes: "City entity page controlled by the cities collection and related structured records.",
  },
  {
    routePattern: "/[citySlug]/destinations/[destinationSlug] and /destinations/[slug]",
    examplePath: "/muscat/destinations/mutrah-corniche",
    classification: "entity",
    conversionAction: "keep-as-entity",
    adminControlled: true,
    preserveIndexedUrl: true,
    risks: [],
    notes: "Destination detail pages are structured entity pages and should not move into topic rendering.",
  },
  {
    routePattern: "/guides/[slug] and /[citySlug]/guides/[guideSlug]",
    examplePath: "/guides/first-time-oman-itinerary",
    classification: "entity",
    conversionAction: "keep-as-entity",
    adminControlled: true,
    preserveIndexedUrl: true,
    risks: [],
    notes: "Guide detail pages are already editorial records and should become the canonical engine for guide-like topics.",
  },
];

export const cityProgrammaticRouteAuditInventory: TopicRouteAuditItem[] = cityProgrammaticPages.map((page) => {
  const classification = classifyCityProgrammaticRoute(page.slug);
  const isThinOrDuplicate = classification === "thin-or-duplicate";
  const risks: TopicPageRisk[] = isThinOrDuplicate
    ? ["admin-control-gap", "duplicate-template", "keyword-only-matching", "thin-content", "future-entity-needed"]
    : ["admin-control-gap", "duplicate-template"];
  const conversionAction: TopicRouteConversionAction = isThinOrDuplicate
    ? "merge-or-prune"
    : "convert-to-guide-engine";

  return {
    routePattern: "/cities/[citySlug]/[seoPage]",
    examplePath: citySeoPath(cityExampleSlug, page.slug),
    classification: classification === "unknown" ? "guide-like-topic" : classification,
    conversionAction,
    adminControlled: false,
    preserveIndexedUrl: true,
    risks,
    notes: isThinOrDuplicate
      ? "Currently generated from keyword-matched structured records. Keep URL available, but only preserve as an indexed page if future editorial guide or dedicated entity data supports it."
      : "Currently generated by config and lists. Preserve the URL and move internal rendering toward guide-engine blocks.",
  };
});

export const topicPageAuditInventory = [
  ...entityRouteAuditInventory,
  ...cityProgrammaticRouteAuditInventory,
];

export function getTopicRouteAuditByPath(pathname: string) {
  return topicPageAuditInventory.find((item) => item.examplePath === pathname);
}
